version: "3.9"

networks:
  raft-net:
    driver: bridge

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      REPLICAS: "http://replica1:3001,http://replica2:3002,http://replica3:3003"
      PORT: "8080"
    networks:
      - raft-net
    volumes:
      - ./gateway:/app
      - /app/node_modules
    depends_on:
      replica1:
        condition: service_healthy
      replica2:
        condition: service_healthy
      replica3:
        condition: service_healthy
    stop_grace_period: 3s
    restart: unless-stopped

  replica1:
    build: ./replica1
    environment:
      NODE_ID: "replica1"
      PORT: "3001"
      PEERS: "http://replica2:3002,http://replica3:3003"
    networks:
      - raft-net
    volumes:
      - ./replica1:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    stop_grace_period: 3s
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3001/status"]
      interval: 1s
      timeout: 500ms
      retries: 5
      start_period: 5s

  replica2:
    build: ./replica2
    environment:
      NODE_ID: "replica2"
      PORT: "3002"
      PEERS: "http://replica1:3001,http://replica3:3003"
    networks:
      - raft-net
    volumes:
      - ./replica2:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    stop_grace_period: 3s
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3002/status"]
      interval: 1s
      timeout: 500ms
      retries: 5
      start_period: 5s

  replica3:
    build: ./replica3
    environment:
      NODE_ID: "replica3"
      PORT: "3003"
      PEERS: "http://replica1:3001,http://replica2:3002"
    networks:
      - raft-net
    volumes:
      - ./replica3:/app
      - /app/node_modules
    ports:
      - "3003:3003"
    stop_grace_period: 3s
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3003/status"]
      interval: 1s
      timeout: 500ms
      retries: 5
      start_period: 5s
